DQNSimEnv:
  n_timesteps: !!float  10000
  policy: 'MultiInputPolicy'
  learning_rate: !!float 0.00856
  batch_size: 64
  buffer_size: 100000
  learning_starts: 0
  gamma: 0.98
  target_update_interval: 20000
  train_freq: 4
  gradient_steps: 8
  exploration_fraction:  0.397
  exploration_final_eps: 0.146
  policy_kwargs: "dict(net_arch=[128, 128])"