DQNSimEnv:
  n_timesteps: !!float  10
  policy: 'MultiInputPolicy'
  learning_rate: !!float 0.00378
  batch_size: 512
  buffer_size: 1000000
  learning_starts: 1000
  gamma: 0.99
  target_update_interval: 20000
  train_freq: 8
  gradient_steps: 1
  exploration_fraction: 0.0967
  exploration_final_eps: 0.01
  policy_kwargs: "dict(net_arch=[128, 128])"