DQNSimEnv:
  n_timesteps: !!float  10
  policy: 'MultiInputPolicy'
  learning_rate: !!float 0.0005
  batch_size: 256
  buffer_size: 100000
  learning_starts: 0
  gamma: 0.95
  target_update_interval: 10000
  train_freq: 16
  gradient_steps: -1
  exploration_fraction: 0.374
  exploration_final_eps: 0.123
  policy_kwargs: "dict(net_arch=[64, 64])"