DQNSimEnv:
  n_timesteps: !!float  10
  policy: 'MultiInputPolicy'
  learning_rate: !!float 8.8e-4
  batch_size: 32
  buffer_size: 10000
  learning_starts: 5000
  gamma: 0.9
  target_update_interval: 20000
  train_freq: 128
  gradient_steps: -1
  exploration_fraction: 0.02
  exploration_final_eps: 0.17
  policy_kwargs: "dict(net_arch=[64, 64])"