SimEnv:
  n_timesteps: !!float  10000
  policy: 'MultiInputPolicy'
  learning_rate: !!float 0.00044
  batch_size: 32
  buffer_size: 1000000
  learning_starts: 20000
  gamma: 0.99
  target_update_interval: 5000
  train_freq: 128
  gradient_steps: -1
  exploration_fraction:  0.341
  exploration_final_eps: 0.085
  policy_kwargs: "dict(net_arch=[128, 128])"