# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from datetime import datetime

# Add project root to path
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../fusion"))

# -- Project information -----------------------------------------------------

project = "FUSION"
copyright = f"2022-{datetime.now().year}, FUSION Development Team"
author = "Arash Rezaee, Ryan McCann, and Vinod M. Vokkarane"
release = "6.0.0"
version = "6.0"

# -- General configuration ---------------------------------------------------

extensions = [
    # Core Sphinx extensions
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.githubpages",
    # Third-party extensions
    "sphinx_rtd_theme",
    "sphinx_copybutton",
    "sphinx_tabs.tabs",
    "myst_parser",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "venv",
    "__pycache__",
]

# The suffix(es) of source filenames.
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document.
master_doc = "index"

# Page title format
html_title = f"{project} {release} Documentation"
html_short_title = f"{project} Docs"

# The language for content autogenerated by Sphinx.
language = "en"

# HTML meta tags for SEO
html_meta = {
    "description": (
        "FUSION: Flexible Unified System for Intelligent Optical "
        "Networking - Open-source simulation framework for Software "
        "Defined Elastic Optical Networks (SD-EONs) with AI integration"
    ),
    "keywords": (
        "optical networks, SDN, elastic optical networks, flex-grid, "
        "simulation, machine learning, reinforcement learning, network "
        "optimization, RMCSA, RSA, software defined networking"
    ),
    "author": "Arash Rezaee, Ryan McCann, and Vinod M. Vokkarane",
    "og:title": ("FUSION - Flexible Unified System for Intelligent Optical Networking"),
    "og:type": "website",
    "og:description": (
        "Open-source simulation framework for Software Defined Elastic "
        "Optical Networks with AI-powered optimization"
    ),
    "og:url": "https://sdnnetsim.github.io/FUSION/",
    "og:site_name": "FUSION Documentation",
    "twitter:card": "summary_large_image",
    "twitter:title": "FUSION - Optical Network Simulation Framework",
    "twitter:description": (
        "Open-source SD-EON simulator with machine learning and "
        "reinforcement learning integration"
    ),
}

# -- Extension configuration -------------------------------------------------

# Napoleon settings (for Google/NumPy style docstrings)
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_type_aliases = None

# Autodoc settings
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
    "show-inheritance": True,
}
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented"
autodoc_mock_imports = []

# Autosummary settings
autosummary_generate = True
autosummary_generate_overwrite = False

# Intersphinx settings (link to other projects' documentation)
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "torch": ("https://pytorch.org/docs/stable/", None),
    "networkx": ("https://networkx.org/documentation/stable/", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "sklearn": ("https://scikit-learn.org/stable/", None),
}

# Todo extension settings
todo_include_todos = True

# Copybutton settings
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True

# MyST parser settings
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "tasklist",
]

# Sphinx-tabs settings
sphinx_tabs_valid_builders = ["html", "linkcheck"]
sphinx_tabs_disable_tab_closing = True

# -- Options for HTML output -------------------------------------------------

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]

# Theme options for sphinx_rtd_theme
html_theme_options = {
    "logo_only": False,
    "display_version": True,
    "prev_next_buttons_location": "bottom",
    "style_external_links": True,
    "vcs_pageview_mode": "",
    "style_nav_header_background": "#2980B9",
    # Toc options
    "collapse_navigation": False,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

# Add custom CSS
html_css_files = [
    "custom.css",
]

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "_static/logo.svg"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/favicon.svg"

# Project links in the sidebar
html_context = {
    "display_github": True,
    "github_user": "SDNNetSim",
    "github_repo": "FUSION",
    "github_version": "main",
    "conf_py_path": "/docs/",
}

# If true, "Created using Sphinx" is shown in the HTML footer.
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer.
html_show_copyright = True

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    "papersize": "letterpaper",
    "pointsize": "10pt",
    "preamble": "",
    "figure_align": "htbp",
}

# Grouping the document tree into LaTeX files.
latex_documents = [
    (master_doc, "FUSION.tex", "FUSION Documentation", author, "manual"),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page.
man_pages = [(master_doc, "fusion", "FUSION Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files.
texinfo_documents = [
    (
        master_doc,
        "FUSION",
        "FUSION Documentation",
        author,
        "FUSION",
        "Flexible Unified System for Intelligent Optical Networking.",
        "Miscellaneous",
    ),
]

# -- Options for Epub output -------------------------------------------------

epub_title = project
epub_exclude_files = ["search.html"]
