SimEnv:
  normalize: true
  n_timesteps: 2000000
  policy: 'MultiInputPolicy'
  n_steps: 5
  gae_lambda: 0.9
  gamma: 0.95
  vf_coef: 0.7
  ent_coef: 0.0000001
  max_grad_norm: 0.75
  learning_rate: 0.00025
  rms_prop_eps: 0.00001
  use_rms_prop: true

  use_sde: false
  sde_sample_freq: -1

  rollout_buffer_class: null
  rollout_buffer_kwargs: null

  stats_window_size: 100
  tensorboard_log: null
  verbose: 0
  policy_kwargs: "dict(
                    ortho_init=True,
                    activation_fn=nn.ReLU,
                    net_arch=dict(pi=[64, 128], vf=[128,64])
                  )"
  _init_setup_model: true
