SimEnv:
  normalize: true
  n_timesteps: 250000

  policy: "MultiInputPolicy"
  learning_rate: 0.0005
  buffer_size: 100000
  learning_starts: 5000
  batch_size: 64
  tau: 1.0
  gamma: 0.99
  train_freq: 1
  gradient_steps: 4
  target_update_interval: 3000

  exploration_initial_eps: 1.0
  exploration_fraction: 0.1
  exploration_final_eps: 0.01

  replay_buffer_class: null
  replay_buffer_kwargs: null
  optimize_memory_usage: false

  max_grad_norm: 10
  policy_kwargs: "dict(net_arch=[256, 128, 64])"
  verbose: 1
  device: cuda
  _init_setup_model: true
