SimEnv:
  normalize: false
  n_timesteps: 1000000
  policy: 'MultiInputPolicy'
  n_steps: 4096
  batch_size: 128
  gae_lambda: 0.92
  gamma: 0.985
  n_epochs: 10
  vf_coef: 0.6
  ent_coef: 0.01
  max_grad_norm: 0.5
  learning_rate: 0.0003
  clip_range: 0.15
  policy_kwargs: "dict(
                    ortho_init=True,
                    activation_fn=nn.ReLU,
                    net_arch=dict(pi=[128,128], vf=[256,256])
                 )"
