SimEnv:
  normalize: false
#  n_envs: 32
  n_timesteps: 250000
  policy: 'MultiInputPolicy'
  n_steps: 512
  batch_size: 128
  gae_lambda: 0.97
  gamma: 0.995
  n_epochs: 5
  vf_coef: 0.5
  ent_coef: 0.0001
#  use_sde: True
  max_grad_norm: 0.5
  learning_rate: 0.001  # Use a constant value for now, schedule can be added in code
#  sde_sample_freq: 4
  clip_range: 0.2
  policy_kwargs: "dict(
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    net_arch=dict(pi=[256,256], vf=[256,256])
                  )"
  callback:
    - rl_scripts.helpers.callback_helpers.GetModelParams:
        verbose: 1
