SimEnv:
  normalize: false
#  n_envs: 32
  n_timesteps: 500000
  policy: 'MultiInputPolicy'
  n_steps: 2048
  batch_size: 128
  gae_lambda: 0.92
  gamma: 0.9
  n_epochs: 10
  vf_coef: 0.6
  ent_coef: 0.000026
#  use_sde: True
  max_grad_norm: 0.6
  learning_rate: 0.019  # Use a constant value for now, schedule can be added in code
#  sde_sample_freq: 4
  clip_range: 0.1
  policy_kwargs: "dict(
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    net_arch=dict(pi=[64,64], vf=[64,64])
                  )"
  callback:
    - reinforcement_learning.utils.callbacks.GetModelParams:
        verbose: 1
