SimEnv:
  normalize: true
  n_timesteps: 2000000
  policy: 'MultiInputPolicy'
  learning_rate: 0.0003
  n_steps: 512
  batch_size: 64
  n_epochs: 10
  gamma: 0.98
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.01
  vf_coef: 0.8
  max_grad_norm: 0.75
  use_sde: false
  sde_sample_freq: -1
  rollout_buffer_class: null
  rollout_buffer_kwargs: null
  target_kl: null
  stats_window_size: 100
  tensorboard_log: null
  policy_kwargs: "dict(
                    ortho_init=True,
                    activation_fn=nn.ReLU,
                    net_arch=dict(pi=[64,256], vf=[256,128])
                 )"
  verbose: 0
  device: cuda
  _init_setup_model: true
