SimEnv:
#  normalize: true
#  n_envs: 32
  n_timesteps: 4000
  policy: 'MultiInputPolicy'
  n_steps: 128
  batch_size: 16
  gae_lambda: 0.92
  gamma: 0.95
  n_epochs: 5
  vf_coef: 0.91
  ent_coef: 0.0056
#  use_sde: True
  max_grad_norm: 0.8
  learning_rate: 0.0006
#  sde_sample_freq: 4
  clip_range: 0.3
  policy_kwargs: "dict(
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    net_arch=dict(pi=[64], vf=[64])
                  )"
  callback:
    - helper_scripts.callback_helpers.GetModelParams:
        verbose: 1
