SimEnv:
  normalize: true
  n_timesteps: 150000

  policy: "MultiInputPolicy"
  learning_rate: 0.000215
  buffer_size: 350000
  learning_starts: 4000
  batch_size: 64
  tau: 0.082
  gamma: 0.928
  train_freq: 1
  gradient_steps: 6
  target_update_interval: 2000

  exploration_initial_eps: 1.0
  exploration_fraction: 0.157
  exploration_final_eps: 0.071

  replay_buffer_class: null
  replay_buffer_kwargs: null
  optimize_memory_usage: false

  max_grad_norm: 9
  stats_window_size: 10
  policy_kwargs: "dict(net_arch=[128, 256, 256], n_quantiles=125)"
  verbose: 0
  device: cuda
  _init_setup_model: true