SimEnv:
  normalize: true
  n_timesteps: 250000

  policy: "MultiInputPolicy"
  learning_rate: 0.0005
  buffer_size: 100000
  learning_starts: 5000
  batch_size: 64
  tau: 0.02
  gamma: 0.95
  train_freq: 2
  gradient_steps: 6
  target_update_interval: 1500

  exploration_initial_eps: 1.0
  exploration_fraction: 0.1
  exploration_final_eps: 0.01

  replay_buffer_class: null
  replay_buffer_kwargs: null
  optimize_memory_usage: false

  max_grad_norm: 10
  stats_window_size: 10
  policy_kwargs: "dict(net_arch=[128, 64], n_quantiles=25)"
  verbose: 1
  _init_setup_model: true

