name: Cross-platform Compatibility Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          
          # Step 1: Install torch first
          pip install torch==2.2.2
          
          # Step 2: Install PyG packages (problematic ones)
          PYG_COMMAND="pip install --no-build-isolation torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://data.pyg.org/whl/torch-2.2.2+cpu.html"
          
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            # Add macOS-specific flags
            echo "Applying macOS build flags..."
            MACOSX_DEPLOYMENT_TARGET=10.15 $PYG_COMMAND
          else
            # Run for Linux and Windows
            $PYG_COMMAND
          fi
          
          # Step 3: Install the rest of the requirements
          # Using a filter to avoid reinstalling packages we just handled
          grep -vE "torch|triton" requirements.txt > other_requirements.txt
          pip install -r other_requirements.txt

      - name: Run Python script
        run: python ./run_sim.py --config_path=ini/example_ini/cross_platform.ini