name: Slack Notifications

on:
  pull_request:
    branches:
      - main
  issues:
    branches:
      - main
  create:
    branches:
      - main
    types: [ tag ]

jobs:

  slack-notifications:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    name: Sends a message to Slack when a pull request, issue, or new tag is made

    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C05LW0SGL6N
          slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}"
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
      - name: Send Slack Message Result
        run: echo "${{ steps.send-message.outputs.slack-result }}"